name: 'Setup VMAF'
description: 'Setup VMAF'
inputs:
  version:  # id of input
    description: 'version'
    required: false
    default: ''
  os:
    description: 'os'
    required: false
    default: ''
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
  name:
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
