name: 'Setup VMAF'
description: 'Setup VMAF'
inputs:
  version: 
    description: 'version of the vmaf, must be tags.'
    required: false
    default: 'v2.1.1'
  prefix:
    description: 'the prefix to install the vmaf'
    required: false
    default: ${{github.workspace}}/libvmaf
runs:
  using: 'node12'
  main: 'dist/index.js'
