name: 'Setup VMAF'
description: 'Setup VMAF'
inputs:
  version: 
    description: 'version of the vmaf, must be master branch or tags.'
    required: false
    default: 'master'
  prefix:
    description: 'the prefix to install the vmaf'
    required: false
    default: ${{github.workspace}}/libvmaf
runs:
  using: 'node12'
  main: 'dist/index.js'
