name: 'Setup VMAF'
description: 'Setup VMAF'
inputs:
  token:
    required: false
  version: 
    description: 'version of the vmaf, must be tags.'
    required: false
    default: 'v2.1.1'
  os:
    description: 'the os that build the libvmaf'
    required: false
    default: ubuntu-20.04
  cc:
    description: 'the compiler that build the libvmaf'
    required: false
    default: gcc
runs:
  using: 'node12'
  main: 'dist/index.js'
