name: libvmaf
on:
  push:
  pull_request:

env:
  DEBIAN_FRONTEND: noninteractive
  VMAFV: v2.1.1
jobs:
  libvmaf-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            CC: ccache gcc
            CXX: ccache g++
            version: ubuntu-18.04-gcc
            osp: ubuntu
          - os: ubuntu-20.04
            CC: ccache gcc
            CXX: ccache g++
            version: ubuntu-20.04-gcc
            osp: ubuntu
          - os: ubuntu-18.04
            CC: ccache clang
            CXX: ccache clang++
            version: ubuntu-18.04-gcc
            osp: ubuntu
          - os: ubuntu-20.04
            CC: ccache clang
            CXX: ccache clang++
            verxion: ubuntu-20.04-clang
            osp: ubuntu
          - os: macos-10.15
            CC: ccache clang
            CXX: ccache clang++
            version: macos-10.15-clang
            osp: macos
            experimental: true
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install meson and ninja
        run: |
          python -m pip install --upgrade pip
          pip install meson

      - name: Install dependencies (ubuntu)
        if: matrix.osp == 'ubuntu'
        run: |
          sudo apt-get update
          sudo -E apt-get -yq install ccache ninja-build
          case "$CC" in
          *gcc) sudo -E apt-get -yq install gcc g++ nasm ;;
          *gcc-9)
            sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
            sudo -E apt-get -yq install gcc-9 g++-9 nasm
            ;;
          *clang) sudo -E apt-get -yq install clang nasm ;;
          esac
          $CC --version
          meson --version
          ccache --version

      - name: Install dependencies (mac)
        if: matrix.osp == 'macos'
        run: |
          brew install -q ninja nasm ccache

          $CC --version
          meson --version
          ccache --version
      
      - name: get vmaf source 
        working-directory: ${{ github.workspace }}
        run: | 
          /usr/bin/git clone https://github.com/Netflix/vmaf.git --branch  v2.1.1 --depth 1
      
      #- name: Run meson
      #  working-directory: ${{github.workspace}}
      #  run: |
      #    meson setup vmaf/libvmaf/build vmaf/libvmaf --buildtype release --prefix ${{github.workspace}}/libvmaf -Denable_float=true
      
      #- name: Run ninja
      #  working-directory: ${{github.workspace}}
      #  run: |
      #    sudo ninja -vC vmaf/libvmaf/build install
      
      - name: package the libvmaf
        working-directory: ${{ github.workspace }}
        run: |
          sudo mkdir libvmaf
          tar czvf "libvmaf-${{ matrix.version }}.tar.gz" libvmaf
      
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/wangwei1237/setup-vmaf/releases/41691505/assets{?name,label}
          asset_path: ${{ github.workspace }}/libvmaf-${{ matrix.version }}.tar.gz
          asset_name: libvmaf-${{ matrix.os }}.tar.gz
          asset_content_type: application/octet-stream
